### PR TITLE
Make sensor groups inverter model aware

### PR DESCRIPTION
**Pull request by rixxxx**
Make sensor groups inverter model aware. Some grid and battery sensor names differ between 1ph, 3ph and 3ph HV models.

Gets rid of annoying messages about missing sensors.
sunsynk-1  | 19:37:45 ERROR   Unknown sensor specified: aux_power
sunsynk-1  | 19:37:45 ERROR   Unknown sensor specified: essential_power
sunsynk-1  | 19:37:45 ERROR   Unknown sensor specified: grid_voltage
sunsynk-1  | 19:37:45 ERROR   Unknown sensor specified: inverter_current
sunsynk-1  | 19:37:45 ERROR   Unknown sensor specified: load_frequency
sunsynk-1  | 19:37:45 ERROR   Unknown sensor specified: non_essential_power

### CODE REVIEW

**Comment by kellerza** [comment]
Thanks @rixxxx 

I made some changes in 2db1d0d which should stop the warnings being issued if sensors in a group is not part of the current definitions. At also adds an "all" group.

Mayb you can extend the definitions further to include all the 3PH sensors?

**Comment by rixxxx** [comment]
Sure, I'll have a look.

**Comment by rixxxx** [comment]
Now I get:
sunsynk-1  | 17:00:14 ERROR   Your config includes deprecated sensors. Replace battery_current with battery_1_current
sunsynk-1  | 17:00:14 ERROR   Your config includes deprecated sensors. Replace battery_power with battery_1_power
sunsynk-1  | 17:00:14 ERROR   Your config includes deprecated sensors. Replace battery_soc with battery_1_soc

battery_current, battery_power and battery_soc get pulled in by power_flow_card. My intention with this PR was to load unnumbered battery sensors only for 1PH and 3PH LV.

**Comment by kellerza** [comment]
https://github.com/kellerza/sunsynk/commit/b86cdf17d22197f23ddfb6ec2574004595b83857

**Comment by rixxxx** [comment]
:clap:

**Pull request closed without merging**
