### PR TITLE
Added battery max charge and discharge sensors

### PR DESCRIPTION
**Pull request by iBeech**
Allows end user to monitor if their charge / discharge rates are being reduced.

@kellerza I'm unsure how to test these changes.

### CODE REVIEW

**Comment by kellerza** [comment]
The best way to test new sensor definitions is to use [custom sensors](https://kellerza.github.io/sunsynk/reference/mysensors)

**Comment by iBeech** [comment]
OK, tested- for some reason, these particular sensors do not work. They just return 0A.

**Comment by iBeech** [comment]
@kellerza resolved. I  was targeting the wrong sensors. These new sensors correctly retrieve the appropriate information. Also resolved some unit test issues

**Comment by kellerza** [comment]
Thanks @iBeech !

**Comment by ap20132022** [comment]
> OK, tested- for some reason, these particular sensors do not work. They just return 0A.

Hi, are you sure, that it works. On the manual, I found that:
210 Max A Charge R/W [0,185] 1A 0-185A
211 Max A discharge R/W [0,185] 1A 0-185A
I have a 12k sg04 (LV Inverter)

**Pull request merged**
