### PR TITLE
Fix multi platform build and add docs

### PR DESCRIPTION
**Pull request by maslyankov**
### PR Description:

**Fixes and Enhancements:**
- Resolved issues with image tagging across different platforms.
- Streamlined the tagging process to support all platforms while maintaining backwards compatibility.
  
**Documentation Update:**
- Added comprehensive documentation for standalone deployment of the `hass-addon-sunsynk-multi` service using Docker Compose and Docker CLI.
- Provided detailed examples for local Docker builds and pre-built images for various architectures (amd64, aarch64, armv7).
- Documented instructions for running the addon alongside `mbusd` on Raspberry Pi and other hosts without requiring Home Assistant.

**Cleanups:**
- Removed unnecessary steps and streamlined the instructions for easier deployment.

This PR ensures smoother multi-platform support and provides clarity for users setting up the addon in standalone environments.

Example packages: https://github.com/maslyankov?tab=packages&repo_name=sunsynk
Example run: https://github.com/maslyankov/sunsynk/actions/runs/11375051809
Docs: https://github.com/maslyankov/sunsynk/blob/improvement/finish-up-multibase-build-workflow/www/docs/guide/standalone-deployment.md

### CODE REVIEW

**Comment by maslyankov** [comment]
@kellerza Any thoughts on this?

**Comment by kellerza** [comment]
Thanks @maslyankov 

I started a first manual run as a test - https://github.com/kellerza/sunsynk/actions/runs/11541954309

Once everything is ok, we probably need the dev version trigger. And then we can comment out the triggers in the old build process

```yaml
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
```

**Comment by kellerza** [comment]
Seems the merge step failed

**Comment by maslyankov** [comment]
> Seems the merge step failed

I will look into it. Can you try to rerun it just in case?

**Pull request merged**
